### ISSUE TITLE
refreshToken() does not work

### ISSUE THREAD

**Issue by thedarkmatter1** [appsscripted/sfconnect#1]
Awesome script! It is about to save my life so thanks for that.

I think there may be some typos in this script, e.g. in refreshToken.gs:

  var clientId = sProps.getProperty('key');
  var clientSecret = sProps.getProperty('secret');

Earlier this was set to sfConsumerKey, sfConsumerSecret in Script properties. Therefore these should be:

  var clientId = sProps.getProperty('sfConsumerKey');
  var clientSecret = sProps.getProperty('sfConsumerSecret');

Also the refresh POST request has "uProps.refresh_token". I think uProps has no property "refresh_token", I think this should be "uProps.access_token" instead.

I am however still getting the following. This is few seconds after getting the new token and fetching a report successfully:

returned code 400. Truncated server response: {"error":"invalid_grant","error_description":"expired access/refresh token"} (use muteHttpExceptions option to examine full response) (line 11, file "refreshToken")

Any ideas will be welcome.

Thanks,

**Comment by thedarkmatter1** [comment]
This is resolved now. Silly me! Wasn't paying attention!

**Comment by appsscripted** [comment]
Thanks for the bugs! Yeah, you're right about sfConsumerKey and sfConsumerSecret.  However, you probably got no refresh token because your connected app did not have the refresh_token OAuth scope.

**Comment by thedarkmatter1** [comment]
Yup. That is what it was. I included refresh_token in the scope of my connected app. And it worked. Thanks so much for this script. Love it!
